// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.0
// source: grpc/consensus.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Nothing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nothing) Reset() {
	*x = Nothing{}
	mi := &file_grpc_consensus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nothing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nothing) ProtoMessage() {}

func (x *Nothing) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_consensus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nothing.ProtoReflect.Descriptor instead.
func (*Nothing) Descriptor() ([]byte, []int) {
	return file_grpc_consensus_proto_rawDescGZIP(), []int{0}
}

type Ok struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lamport       uint32                 `protobuf:"varint,1,opt,name=lamport,proto3" json:"lamport,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ok) Reset() {
	*x = Ok{}
	mi := &file_grpc_consensus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ok) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ok) ProtoMessage() {}

func (x *Ok) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_consensus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ok.ProtoReflect.Descriptor instead.
func (*Ok) Descriptor() ([]byte, []int) {
	return file_grpc_consensus_proto_rawDescGZIP(), []int{1}
}

func (x *Ok) GetLamport() uint32 {
	if x != nil {
		return x.Lamport
	}
	return 0
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lamport       uint32                 `protobuf:"varint,1,opt,name=lamport,proto3" json:"lamport,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_grpc_consensus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_consensus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_grpc_consensus_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetLamport() uint32 {
	if x != nil {
		return x.Lamport
	}
	return 0
}

func (x *Request) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Request) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

var File_grpc_consensus_proto protoreflect.FileDescriptor

const file_grpc_consensus_proto_rawDesc = "" +
	"\n" +
	"\x14grpc/consensus.proto\x12\x04grpc\"\t\n" +
	"\aNothing\"\x1e\n" +
	"\x02Ok\x12\x18\n" +
	"\alamport\x18\x01 \x01(\rR\alamport\"G\n" +
	"\aRequest\x12\x18\n" +
	"\alamport\x18\x01 \x01(\rR\alamport\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port2k\n" +
	"\x10ConsensusService\x12(\n" +
	"\rAcceptRequest\x12\b.grpc.Ok\x1a\r.grpc.Nothing\x12-\n" +
	"\rRequestAccess\x12\r.grpc.Request\x1a\r.grpc.NothingB\x13Z\x11consensus-go/grpcb\x06proto3"

var (
	file_grpc_consensus_proto_rawDescOnce sync.Once
	file_grpc_consensus_proto_rawDescData []byte
)

func file_grpc_consensus_proto_rawDescGZIP() []byte {
	file_grpc_consensus_proto_rawDescOnce.Do(func() {
		file_grpc_consensus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_consensus_proto_rawDesc), len(file_grpc_consensus_proto_rawDesc)))
	})
	return file_grpc_consensus_proto_rawDescData
}

var file_grpc_consensus_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_consensus_proto_goTypes = []any{
	(*Nothing)(nil), // 0: grpc.Nothing
	(*Ok)(nil),      // 1: grpc.Ok
	(*Request)(nil), // 2: grpc.Request
}
var file_grpc_consensus_proto_depIdxs = []int32{
	1, // 0: grpc.ConsensusService.AcceptRequest:input_type -> grpc.Ok
	2, // 1: grpc.ConsensusService.RequestAccess:input_type -> grpc.Request
	0, // 2: grpc.ConsensusService.AcceptRequest:output_type -> grpc.Nothing
	0, // 3: grpc.ConsensusService.RequestAccess:output_type -> grpc.Nothing
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_consensus_proto_init() }
func file_grpc_consensus_proto_init() {
	if File_grpc_consensus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_consensus_proto_rawDesc), len(file_grpc_consensus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_consensus_proto_goTypes,
		DependencyIndexes: file_grpc_consensus_proto_depIdxs,
		MessageInfos:      file_grpc_consensus_proto_msgTypes,
	}.Build()
	File_grpc_consensus_proto = out.File
	file_grpc_consensus_proto_goTypes = nil
	file_grpc_consensus_proto_depIdxs = nil
}
