// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/idk.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Message_Request
	//	*Message_Reply
	Payload       isMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_idk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_idk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_idk_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetPayload() isMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetRequest() *Request {
	if x != nil {
		if x, ok := x.Payload.(*Message_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *Message) GetReply() *Reply {
	if x != nil {
		if x, ok := x.Payload.(*Message_Reply); ok {
			return x.Reply
		}
	}
	return nil
}

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_Request struct {
	Request *Request `protobuf:"bytes,1,opt,name=request,proto3,oneof"`
}

type Message_Reply struct {
	Reply *Reply `protobuf:"bytes,2,opt,name=reply,proto3,oneof"`
}

func (*Message_Request) isMessage_Payload() {}

func (*Message_Reply) isMessage_Payload() {}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_idk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_idk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_idk_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Request) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Reply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RequestTimestamp uint64                 `protobuf:"varint,2,opt,name=request_timestamp,json=requestTimestamp,proto3" json:"request_timestamp,omitempty"` // Timestamp of the request this is replying to, so the `Node` knows if its an ack to its current req and not an old one
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_proto_idk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_idk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_proto_idk_proto_rawDescGZIP(), []int{2}
}

func (x *Reply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Reply) GetRequestTimestamp() uint64 {
	if x != nil {
		return x.RequestTimestamp
	}
	return 0
}

var File_proto_idk_proto protoreflect.FileDescriptor

const file_proto_idk_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/idk.proto\x12\x05proto\"f\n" +
	"\aMessage\x12*\n" +
	"\arequest\x18\x01 \x01(\v2\x0e.proto.RequestH\x00R\arequest\x12$\n" +
	"\x05reply\x18\x02 \x01(\v2\f.proto.ReplyH\x00R\x05replyB\t\n" +
	"\apayload\"7\n" +
	"\aRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\"D\n" +
	"\x05Reply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x11request_timestamp\x18\x02 \x01(\x04R\x10requestTimestamp2E\n" +
	"\x15RicartAgrawalaService\x12,\n" +
	"\x06Stream\x12\x0e.proto.Message\x1a\x0e.proto.Message(\x010\x01B.Z,github.com/augustlh/ricart-agrawala-go/protob\x06proto3"

var (
	file_proto_idk_proto_rawDescOnce sync.Once
	file_proto_idk_proto_rawDescData []byte
)

func file_proto_idk_proto_rawDescGZIP() []byte {
	file_proto_idk_proto_rawDescOnce.Do(func() {
		file_proto_idk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_idk_proto_rawDesc), len(file_proto_idk_proto_rawDesc)))
	})
	return file_proto_idk_proto_rawDescData
}

var file_proto_idk_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_idk_proto_goTypes = []any{
	(*Message)(nil), // 0: proto.Message
	(*Request)(nil), // 1: proto.Request
	(*Reply)(nil),   // 2: proto.Reply
}
var file_proto_idk_proto_depIdxs = []int32{
	1, // 0: proto.Message.request:type_name -> proto.Request
	2, // 1: proto.Message.reply:type_name -> proto.Reply
	0, // 2: proto.RicartAgrawalaService.Stream:input_type -> proto.Message
	0, // 3: proto.RicartAgrawalaService.Stream:output_type -> proto.Message
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_idk_proto_init() }
func file_proto_idk_proto_init() {
	if File_proto_idk_proto != nil {
		return
	}
	file_proto_idk_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_Request)(nil),
		(*Message_Reply)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_idk_proto_rawDesc), len(file_proto_idk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_idk_proto_goTypes,
		DependencyIndexes: file_proto_idk_proto_depIdxs,
		MessageInfos:      file_proto_idk_proto_msgTypes,
	}.Build()
	File_proto_idk_proto = out.File
	file_proto_idk_proto_goTypes = nil
	file_proto_idk_proto_depIdxs = nil
}
