// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/idk.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RicartAgrawalaService_Stream_FullMethodName = "/proto.RicartAgrawalaService/Stream"
)

// RicartAgrawalaServiceClient is the client API for RicartAgrawalaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RicartAgrawalaServiceClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Message, Message], error)
}

type ricartAgrawalaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRicartAgrawalaServiceClient(cc grpc.ClientConnInterface) RicartAgrawalaServiceClient {
	return &ricartAgrawalaServiceClient{cc}
}

func (c *ricartAgrawalaServiceClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Message, Message], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RicartAgrawalaService_ServiceDesc.Streams[0], RicartAgrawalaService_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Message, Message]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RicartAgrawalaService_StreamClient = grpc.BidiStreamingClient[Message, Message]

// RicartAgrawalaServiceServer is the server API for RicartAgrawalaService service.
// All implementations must embed UnimplementedRicartAgrawalaServiceServer
// for forward compatibility.
type RicartAgrawalaServiceServer interface {
	Stream(grpc.BidiStreamingServer[Message, Message]) error
	mustEmbedUnimplementedRicartAgrawalaServiceServer()
}

// UnimplementedRicartAgrawalaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRicartAgrawalaServiceServer struct{}

func (UnimplementedRicartAgrawalaServiceServer) Stream(grpc.BidiStreamingServer[Message, Message]) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedRicartAgrawalaServiceServer) mustEmbedUnimplementedRicartAgrawalaServiceServer() {}
func (UnimplementedRicartAgrawalaServiceServer) testEmbeddedByValue()                               {}

// UnsafeRicartAgrawalaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RicartAgrawalaServiceServer will
// result in compilation errors.
type UnsafeRicartAgrawalaServiceServer interface {
	mustEmbedUnimplementedRicartAgrawalaServiceServer()
}

func RegisterRicartAgrawalaServiceServer(s grpc.ServiceRegistrar, srv RicartAgrawalaServiceServer) {
	// If the following call pancis, it indicates UnimplementedRicartAgrawalaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RicartAgrawalaService_ServiceDesc, srv)
}

func _RicartAgrawalaService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RicartAgrawalaServiceServer).Stream(&grpc.GenericServerStream[Message, Message]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RicartAgrawalaService_StreamServer = grpc.BidiStreamingServer[Message, Message]

// RicartAgrawalaService_ServiceDesc is the grpc.ServiceDesc for RicartAgrawalaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RicartAgrawalaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RicartAgrawalaService",
	HandlerType: (*RicartAgrawalaServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _RicartAgrawalaService_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/idk.proto",
}
