// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/ricart_agrawala.proto

package cs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RA_Hello_FullMethodName   = "/ra.RA/Hello"
	RA_Request_FullMethodName = "/ra.RA/Request"
	RA_Reply_FullMethodName   = "/ra.RA/Reply"
)

// RAClient is the client API for RA service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RAClient interface {
	Hello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloResp, error)
	Request(ctx context.Context, in *RequestMsg, opts ...grpc.CallOption) (*Ack, error)
	Reply(ctx context.Context, in *ReplyMsg, opts ...grpc.CallOption) (*Ack, error)
}

type rAClient struct {
	cc grpc.ClientConnInterface
}

func NewRAClient(cc grpc.ClientConnInterface) RAClient {
	return &rAClient{cc}
}

func (c *rAClient) Hello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResp)
	err := c.cc.Invoke(ctx, RA_Hello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rAClient) Request(ctx context.Context, in *RequestMsg, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, RA_Request_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rAClient) Reply(ctx context.Context, in *ReplyMsg, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, RA_Reply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RAServer is the server API for RA service.
// All implementations must embed UnimplementedRAServer
// for forward compatibility.
type RAServer interface {
	Hello(context.Context, *HelloReq) (*HelloResp, error)
	Request(context.Context, *RequestMsg) (*Ack, error)
	Reply(context.Context, *ReplyMsg) (*Ack, error)
	mustEmbedUnimplementedRAServer()
}

// UnimplementedRAServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRAServer struct{}

func (UnimplementedRAServer) Hello(context.Context, *HelloReq) (*HelloResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedRAServer) Request(context.Context, *RequestMsg) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedRAServer) Reply(context.Context, *ReplyMsg) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reply not implemented")
}
func (UnimplementedRAServer) mustEmbedUnimplementedRAServer() {}
func (UnimplementedRAServer) testEmbeddedByValue()            {}

// UnsafeRAServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RAServer will
// result in compilation errors.
type UnsafeRAServer interface {
	mustEmbedUnimplementedRAServer()
}

func RegisterRAServer(s grpc.ServiceRegistrar, srv RAServer) {
	// If the following call pancis, it indicates UnimplementedRAServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RA_ServiceDesc, srv)
}

func _RA_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RA_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAServer).Hello(ctx, req.(*HelloReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RA_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RA_Request_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAServer).Request(ctx, req.(*RequestMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _RA_Reply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplyMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAServer).Reply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RA_Reply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAServer).Reply(ctx, req.(*ReplyMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// RA_ServiceDesc is the grpc.ServiceDesc for RA service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RA_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ra.RA",
	HandlerType: (*RAServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _RA_Hello_Handler,
		},
		{
			MethodName: "Request",
			Handler:    _RA_Request_Handler,
		},
		{
			MethodName: "Reply",
			Handler:    _RA_Reply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ricart_agrawala.proto",
}
