// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/ricart_agrawala.proto

package cs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReq) Reset() {
	*x = HelloReq{}
	mi := &file_proto_ricart_agrawala_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReq) ProtoMessage() {}

func (x *HelloReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ricart_agrawala_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReq.ProtoReflect.Descriptor instead.
func (*HelloReq) Descriptor() ([]byte, []int) {
	return file_proto_ricart_agrawala_proto_rawDescGZIP(), []int{0}
}

func (x *HelloReq) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *HelloReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type HelloResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*Peer                `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResp) Reset() {
	*x = HelloResp{}
	mi := &file_proto_ricart_agrawala_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResp) ProtoMessage() {}

func (x *HelloResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ricart_agrawala_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResp.ProtoReflect.Descriptor instead.
func (*HelloResp) Descriptor() ([]byte, []int) {
	return file_proto_ricart_agrawala_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResp) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_proto_ricart_agrawala_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ricart_agrawala_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_proto_ricart_agrawala_proto_rawDescGZIP(), []int{2}
}

func (x *Peer) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Peer) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type RequestMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          int32                  `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	Ts            int64                  `protobuf:"varint,2,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMsg) Reset() {
	*x = RequestMsg{}
	mi := &file_proto_ricart_agrawala_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMsg) ProtoMessage() {}

func (x *RequestMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ricart_agrawala_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMsg.ProtoReflect.Descriptor instead.
func (*RequestMsg) Descriptor() ([]byte, []int) {
	return file_proto_ricart_agrawala_proto_rawDescGZIP(), []int{3}
}

func (x *RequestMsg) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *RequestMsg) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type ReplyMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          int32                  `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	Ts            int64                  `protobuf:"varint,2,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyMsg) Reset() {
	*x = ReplyMsg{}
	mi := &file_proto_ricart_agrawala_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMsg) ProtoMessage() {}

func (x *ReplyMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ricart_agrawala_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMsg.ProtoReflect.Descriptor instead.
func (*ReplyMsg) Descriptor() ([]byte, []int) {
	return file_proto_ricart_agrawala_proto_rawDescGZIP(), []int{4}
}

func (x *ReplyMsg) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *ReplyMsg) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_ricart_agrawala_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ricart_agrawala_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_ricart_agrawala_proto_rawDescGZIP(), []int{5}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_proto_ricart_agrawala_proto protoreflect.FileDescriptor

const file_proto_ricart_agrawala_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/ricart_agrawala.proto\x12\x02ra\"0\n" +
	"\bHelloReq\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\"+\n" +
	"\tHelloResp\x12\x1e\n" +
	"\x05peers\x18\x01 \x03(\v2\b.ra.PeerR\x05peers\",\n" +
	"\x04Peer\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\"0\n" +
	"\n" +
	"RequestMsg\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x05R\x04from\x12\x0e\n" +
	"\x02ts\x18\x02 \x01(\x03R\x02ts\".\n" +
	"\bReplyMsg\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x05R\x04from\x12\x0e\n" +
	"\x02ts\x18\x02 \x01(\x03R\x02ts\"\x15\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2n\n" +
	"\x02RA\x12$\n" +
	"\x05Hello\x12\f.ra.HelloReq\x1a\r.ra.HelloResp\x12\"\n" +
	"\aRequest\x12\x0e.ra.RequestMsg\x1a\a.ra.Ack\x12\x1e\n" +
	"\x05Reply\x12\f.ra.ReplyMsg\x1a\a.ra.AckB\x1aZ\x18ricart_agrawala/proto;csb\x06proto3"

var (
	file_proto_ricart_agrawala_proto_rawDescOnce sync.Once
	file_proto_ricart_agrawala_proto_rawDescData []byte
)

func file_proto_ricart_agrawala_proto_rawDescGZIP() []byte {
	file_proto_ricart_agrawala_proto_rawDescOnce.Do(func() {
		file_proto_ricart_agrawala_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ricart_agrawala_proto_rawDesc), len(file_proto_ricart_agrawala_proto_rawDesc)))
	})
	return file_proto_ricart_agrawala_proto_rawDescData
}

var file_proto_ricart_agrawala_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_ricart_agrawala_proto_goTypes = []any{
	(*HelloReq)(nil),   // 0: ra.HelloReq
	(*HelloResp)(nil),  // 1: ra.HelloResp
	(*Peer)(nil),       // 2: ra.Peer
	(*RequestMsg)(nil), // 3: ra.RequestMsg
	(*ReplyMsg)(nil),   // 4: ra.ReplyMsg
	(*Ack)(nil),        // 5: ra.Ack
}
var file_proto_ricart_agrawala_proto_depIdxs = []int32{
	2, // 0: ra.HelloResp.peers:type_name -> ra.Peer
	0, // 1: ra.RA.Hello:input_type -> ra.HelloReq
	3, // 2: ra.RA.Request:input_type -> ra.RequestMsg
	4, // 3: ra.RA.Reply:input_type -> ra.ReplyMsg
	1, // 4: ra.RA.Hello:output_type -> ra.HelloResp
	5, // 5: ra.RA.Request:output_type -> ra.Ack
	5, // 6: ra.RA.Reply:output_type -> ra.Ack
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_ricart_agrawala_proto_init() }
func file_proto_ricart_agrawala_proto_init() {
	if File_proto_ricart_agrawala_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ricart_agrawala_proto_rawDesc), len(file_proto_ricart_agrawala_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ricart_agrawala_proto_goTypes,
		DependencyIndexes: file_proto_ricart_agrawala_proto_depIdxs,
		MessageInfos:      file_proto_ricart_agrawala_proto_msgTypes,
	}.Build()
	File_proto_ricart_agrawala_proto = out.File
	file_proto_ricart_agrawala_proto_goTypes = nil
	file_proto_ricart_agrawala_proto_depIdxs = nil
}
